--- #NGINX

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: create cache directory
  file:
    path: /usr/share/nginx/cache/fcgi
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes

- name: Copy nginx configuration for wordpress
  template:
    src: wordpress.conf
    dest: /etc/nginx/conf.d/{{hostname}}.conf
    # force: yes
  notify:
    restart nginx

# - name: Copy nginx ssl configuration for wordpress
#   template:
#     src: wordpress
#     dest: /etc/nginx/sites-available/wordpress-ssl
#     force: yes
#   notify:
#     restart nginx

- name: Copy nginx general configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy nginx logrotate config
  template:
    src: logrotate
    dest: /etc/logrotate.d/nginx
  notify: restart nginx

- name: Delete default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    reload nginx
