---
- name: Install php-fpm
  apt:
    name: "{{packages}}"
    state: latest
  vars:
    packages:
    - php7.0-fpm
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-json
    - php7.0-dev
    - php7.0-mcrypt
    - php7.0-curl
    - php7.0-gd
    - php7.0-xmlrpc
    - php7.0-xml
  notify:
    - restart php7.0-fpm

- name: Disable default pool
  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.conf.bak creates=/etc/php/7.0/fpm/pool.d/www.conf.bak
  notify: restart php7.0-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php/7.0/fpm/pool.d
  notify:
    stop php7.0-fpm
    restart php7.0-fpm
#
#Configure and secure php.ini

- name: php.ini - Change max upload size to 25M
  replace: dest=/etc/php/7.0/fpm/php.ini regexp='^upload_max_filesize = .*$' replace='upload_max_filesize = 25M'
  notify: restart php7.0-fpm

- name: php.ini - Change memory limit to 256M
  replace: dest=/etc/php/7.0/fpm/php.ini regexp='^memory_limit = .*$' replace='memory_limit = 256M'
  notify: restart php7.0-fpm

- name: php.ini - Ensure php7.0-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify: restart php7.0-fpm
#
# - name: Download composer
#   get_url:
#     url: https://getcomposer.org/installer
#     dest: /tmp/installer
#
# - name: Install composer
#   shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
#   args:
#     creates: /usr/local/bin/composer
#
# - name: Rename composer.phar to composer
#   shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
#   args:
#     creates: /usr/local/bin/composer
#
# - name: Make composer executable
#   file:
#     path: /usr/local/bin/composer
#     mode: a+x
#     state: file
#     owner: {{user}}
