---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM on Debian 10
  hosts: all
  user: ansible
  become: yes

  roles:
    - debian
    - users
      # ssh
    - nginx
    - php-fpm
    # mariadb
    # - wpcli
    # - letsencrypt

#---
# - name: Include vars
#   include_vars:
#     dir: vars
#     name: all
