---
- name: Set hostname
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1[ \t]localhost'
    line: "127.0.0.1  {{hostname}}"
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
