---
- name: Set hostname
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1[ \t]localhost'
    line: "127.0.0.1  {{hostname}}"
    state: present
    backup: yes

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: apt-get upgrade && update
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400

- name: Install essentials
  apt:
    name: "{{packages}}"
  vars:
    packages:
    # - python-apt
    - git
    - net-tools
    - locate
    - tree
    - htop
    - tmux
    - fail2ban
    - mysqltuner
