#https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/setup-Debian.yml
---
- name: Install MariaDB package
  apt:
    name: "{{packages}}"
  vars:
    packages:
      - mariadb-server
      - mariadb-common
      - libmariadb-dev
      # - python-pip
      # - mysqltuner
      - mycli
      - python-pymysql
      # - python-mysqldb
      # - default-libmysqlclient-dev
      - mydumper
    state: latest

# - name: Install Pymysql via pip3
#   pip:
#     name: pymysql

- name: Copy my.cnf
  template:
    src: my.cnf
    dest: /etc/mysql/my.cnf
    force: yes
  notify:
    restart mariadb

- name: Start mariadb
  service:
    name: MariaDB
    state: restarted

# - name: Create a new database
#   mysql_db:
#     name: "{{wp_db_name}}"
#     state: present

- name: Create database user
  mysql_user:
    name: "{{mysql_user}}"
    password: "{{mysql_user_password}}"
    priv: '*.*:ALL'
    state: present

- name: Delete anonymous MySQL server user for localhost
  mysql_user:
    name: ''
    host_all: yes
    state: absent


# # localhost needs to be the last item for idempotency
# - name: Update mysql root password for all root accounts
#   mysql_user:
#     name: root
#     host: {{ item }}
#     password: {{ mysql_root_password }}
#   with_items:
#     - "{{ ansible_hostname }}"
#     - 127.0.0.1
#     - ::1
#     - localhost
