---
- name: Install MariaDB package
  apt:
    name: "{{packages}}"
  vars:
    packages:
      - mariadb-server
      - default-libmysqlclient-dev
      - python3-mysqldb
      # - python-pymysql
    state: latest

- name: Create a new database
  mysql_db:
    name: "{{wp_db_name}}"
    state: present

- name: Create database user
  mysql_user:
    name: "{{mysql_user}}"
    password: "{{mysql_user_password}}"
    priv: '*.*:ALL'
    state: present

- name: Copy my.cnf
  template:
    src: my.cnf
    dest: /etc/mysql/my.cnf
    # force: yes
  notify:
    restart mysql

- name: Delete anonymous MySQL server user for localhost
  mysql_user:
    name: ''
    host_all: yes
    state: absent


# # localhost needs to be the last item for idempotency
# - name: Update mysql root password for all root accounts
#   mysql_user:
#     name: root
#     host: {{ item }}
#     password: {{ mysql_root_password }}
#   with_items:
#     - "{{ ansible_hostname }}"
#     - 127.0.0.1
#     - ::1
#     - localhost
