---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded enabled=yes

- name: stop nginx
  service: name=nginx state=stopped enabled=yes

