---
- name: Install Certbot
  apt:
    name: "{{packages}}"
    # state: latest
  vars:
    packages:
      - certbot
      - python-certbot-nginx

- name: Install ssl_certificate
  command: certbot --nginx certonly

# - name: Download and install certbot
#   get_url: url=https://dl.eff.org/certbot-auto dest=/usr/local/bin/certbot-auto mode=0770
#
# - name: Add line to crontab for auto renewal
#   cron: name="cert renew" minute="0" hour="*/12" job="/usr/local/bin/certbot-auto renew" user=root
